### ISSUE TITLE
Result of call to xxx is unused

### ISSUE THREAD

**Issue by lanceylai** [ankurp/Cent#16]
Some of the function do not need the result value. So could you please modify them to use`@discardableResult`?

**Comment by ankurp** [comment]
Thanks will look into this.

**Comment by tsheaff** [comment]
Want to +1 this.

I'm currently having to do add `_ =` in order to avoid the result, for example:

``` swift
_ = array.eachWithIndex { ... }
```

When `...` is just performing a task and I don't care about the result

**Comment by ankurp** [comment]
Created a branch for this. Will merge after testing and publish it as `6.0.3` https://github.com/ankurp/Cent/pull/20
