### ISSUE TITLE
What about the Xcod8 beta and Swift3 Support?

### ISSUE THREAD

**Issue by scottlaw** [ankurp/Cent#9]
What about the Xcod8 beta and Swift3 Support?

/Pods/Cent/Sources/String.swift:82:16: Value of type 'String' has no member 'substringWithRange'
/Pods/Cent/Sources/String.swift:134:16: Value of type 'String' has no member 'stringByTrimmingCharactersInSet'

...

**Comment by ankurp** [comment]
Will take a look and create a swift-3 branch.

**Comment by A1iAshoor** [comment]
+1 urgent call guys

**Comment by ankurp** [comment]
@A1iAshoor Upgrading today.

**Comment by ankurp** [comment]
Created swift-3 branch but need to fix all the test. #12

**Comment by zstrenfel** [comment]
hi, when i pull from the swift-3 branch i still get conflicting requirements:

`pod 'Dollar', '~> 6.0.0'`
`pod 'Cent', :git => 'https://github.com/ankurp/Cent.git', :branch => 'swift-3'`
- `Dollar (~> 6.0.0)` required by `Podfile`
- `Dollar (~> 5.2.0)` required by `Cent (5.0.3)`

**Comment by ankurp** [comment]
I need to update the podspec. Updating soon.

**Comment by ankurp** [comment]
I pushed an update to the swift-3 branch to include the updated podspec to use Dollar 6.0.0

**Comment by lanceylai** [comment]
@ankurp  +1.  When do you release a new version?

**Comment by ankurp** [comment]
Once I get the test working I will release. May this weekend.

**Comment by lauracpierre** [comment]
@ankurp you're doing an awesome job with this repo. I see you've been updating it today, thanks again for this. 

Linking to swift-3 branch right now in podfile until you finish fixing all the tests. Thanks again!

**Comment by ankurp** [comment]
@lauracpierre Thanks let me know if you run into any issues. I am thinking of releasing the 6.0.0 version soon which will have swift-3 changes.

**Comment by lauracpierre** [comment]
Wonderful ! 
It worked great with the swift3 branch. 

(I think... I'm still correcting the 358+ errors generated by the migration tool 😅)

**Comment by ankurp** [comment]
`6.0.0` version is published on cocoapods which support Swift 3 syntax. Closing this issue.
https://cocoapods.org/pods/Cent
